### PR TITLE
Begin using develop branch

### PR DESCRIPTION
**Pull request by eonist**

### CODE REVIEW

**Comment by eonist** [comment]
@blurtime 
- Use develop branch in Carthage so you can test and code efficient. I sent you a collab invite for the repo so you can add code directly.
- Then maybe make PR's from dev to master once they are tested and reviewed etc. we will see what is easiest
- I made an overview of different framework workflows http://eon.codes/blog/2019/07/22/Framework-workflows/ Some gotchas in there, even tho you probably know the basics by now.
- Kind of crazy that you are working on AVFoundation stuff and still in school. ✨

**Comment by blurtime** [comment]
Awesome, thanks for the invitation! I'll make sure to set everything up right away! 
Yeah, I guess I know some basics now but I'll ask a question here and there if I'm not sure about something, hope that's ok 😅
Thank you! 😃 I'm very motivated to code right now 😌

**Comment by blurtime** [comment]
I've set everything up now. Had to change the part you cleaned up earlier, unfortunately, though. It didn't compile... 
I'm now going to look into the long-press zoom part. Would really appreciate if you could take look at `onPreviewViewDoubleTap` in the `CamView+Gesture.swift` since I couldn't figure out how to let the button know, too, that the camera was flipped. Moreover and more importantly, one also needs to adjust the. I just set it to `.back` yesterday just to test it out. But of course, it should always flip to the other one than the currently used one... 😅

**Comment by eonist** [comment]
You have to make a callback for the flip button. To make it aware. Var onCamFlip:(Bool)->void = {}

**Comment by eonist** [comment]
You can look at the longpress functionality in the recBtn. Maybe cooy that code and use it for the previewView. Im working on AnimLib atm. Could be interesting to combined it with HybridCamera. Some fancy next gen UX/UI animation in a camApp https://github.com/eonist/AnimLib/

**Comment by blurtime** [comment]
So I managed to add the UILongPressGesture for the zooming to the button. I just tried it out and it works like a charm 🤓 I'll commit the changes to the develop branch right away so you can test it out, too, if you'd like to
Could you show me how to make this callback? I'm not entirely sure how you would approach this, as your style of coding is very different from mine. I'm still trying to get used to the way you handle things in your code. That's also part of the reason why it took me so long to add the long-press to zoom just now. 😅 Seems like that's another thing I'm not entirely able to do on my own besides the flipping the camera while recording :/ 
Sure, could be very interesting to have some fancy animation here and there!

**Comment by eonist** [comment]
Pseudo-code:
```swift
MainView {
	func init() {
		let button = :init()
		let camView = .init()
		camView.onLongPress = button.setFlippedState // Hocks up the call-back
	}
}
Button {
	func setFlippedState(isFlipped: Bool) {
		self.image = isFlipped ? .on : .of
	}
}
CamView {
	 var isForward: Bool = false
	 var onCamFlip: (Bool) -> Void = {} // the call-back
	 func onLongPress() {
	 	onCamFlip(!isForward) // Notifies whatever is registered in the call-back
	 }
}
```

**Comment by eonist** [comment]
Using call-backs is much better than NSNotification or Delegates etc. Call-backs are easy to reason about. In depth analysis of call-back based architecture: https://medium.cobeisfresh.com/why-you-shouldn-t-use-delegates-in-swift-7ef808a7f16b

**Comment by blurtime** [comment]
I saw this post already since you linked it in the README. The callbacks are one of the reasons why I love this pod so much. The code you wrote is seriously awesome! I haven't coded that much using call-backs, though, so I sometimes I struggle a little and may need some help. So thank you for posting the code up there, really appreciate it! 😅👍 I'll try to finish that issue tomorrow. Have you already tried out the long-press to zoom? I'm gonna test it real quick again just to make sure it's working and then merge it if everything seems alright.

**Comment by eonist** [comment]
- Just keep working on develop until it finds it form. Then when your happy / confident I will refactor before we merge to master.
- I will test further down the line. If something isn't 100% I will make it 100%  with some research / refactoring

**Comment by eonist** [comment]
The great thing about call-backs is that it works in all languages. So the knowledge is transferable to other languages you may want to use. I use a lot of callbacks in Javascript for instance.

**Comment by eonist** [comment]
Here is how you can install swift-lint for Xcode btw: http://eon.codes/blog/2019/04/23/Swift-lint/ 

It will make you a stronger developer in day-1 and you will keep getting better. Also makes code universal between developers. Over time we tend to stray with code-style and code-isms

**Comment by blurtime** [comment]
Totally forgot installing it... :o I'll do it right away. 
I am going to create a new PR for the long-press to zoom now (like you said: rather more PRs than one huge one). I tried to stick with your style of coding as much as I could. So I hope there isn't too much additional work needed 😅

**Comment by eonist** [comment]
Small PR's are good.

**Pull request merged**
