### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by blurtime**
This PR contains: 

1. reset zoom after recording
2. switch between audio sessions such that audio has normal volume when replaying in `processMediaView`
3. memory leak virtually fixed

Regarding the memory leak:
- I added a few further changes which have now reduced it even more (in `VideoPlayerView.swift` and `ProcessView+Event.swift`)
- there are still some mallocs of a couple of hundred bytes leaking here and there but that's almost nothing

Carthage still works fine and is building. 

Suggestion: 
You said you wanted to add animations. Maybe one could move the `self.resetZoom` into the `.onExit` closure as originally suggested and instead of suddenly resetting it, zoom out using animations. (I thought putting it outside would fix it. But now one sees how the zoom is suddenly reset shortly before (instead of after) being presented the process media view which I apparently didn't notice yesterday.)

### CODE REVIEW

**Comment by eonist** [comment]
Regarding zoom out glitch. I suggest we Add a small delay of say 0.2sec. To give the chance to zoom out before showing virwfinder

**Comment by eonist** [comment]
Actually. What about restetorget zoom when you go from viewfinder to review mode?

**Comment by blurtime** [comment]
Sure, sounds good 👍 would either do that or the animation as I mentioned (although I would prefer the former).

**Comment by eonist** [comment]
The expectee  behaviour is to be in zoom 1x once you restart the camera. Similar to how other cam apps work. IMO

**Comment by blurtime** [comment]
That's what I'm saying: I'd prefer immediately being zoomed in at 1x over animations, too. 😅 I usually try to make people feel it's as natural as possible...

**Comment by eonist** [comment]
- Added the doubleClick to flip cam feature. I figured out how to derive the position from apples framework, instead of storing it in CamView etc. 
- Also cleaned up bits and pieces. 
- I will test with the iPhone tomorrow

**Comment by blurtime** [comment]
Sounds awesome! 🎉 I bet this library will do a lot better now, too :) I know CocoaPods is finicky to set up but adding it at some point would definitely help this library even more (as we've seen a few days ago when I was still a carthage noob :D)

**Comment by eonist** [comment]
Yeah. I totally agree. I need to start adding cocoaPods. Seems people are addicted to pods. I have to relearn how set it up tho, cuz i forgot. 🤦

**Comment by blurtime** [comment]
Fortunately, it isn't important in my case anymore since I'm now a carthage expert 😄 But many others will probably have a hard time when confronted with carthage for the first time, too...
Anyway, if you should work on this project anytime soon again, adding support for flipping the camera while recording would really seal the deal with regards to advantages over other camera libraries. If I have some time next month (around mid-August) I'll try to add this feature.
Keep up the great work! 👍

**Comment by eonist** [comment]
Yeah. that's a pretty cool feature. Like your filming something and then you could show your reaction etc. Does insta and snap have this?

**Comment by blurtime** [comment]
Yeah, they both do. It was somewhat big news when Snap introduced it. Especially doing it [this way](https://stackoverflow.com/questions/13951182/audio-video-out-of-sync-after-switch-camera/54770398#54770398) sounds pretty nifty since you should be able to switch very quickly between the cameras which as far as I know still is a little problematic in Snap and Instagram because the recording usually seems to be interrupted for a small amount of time so all you see is a black screen for a moment.

**Comment by eonist** [comment]
Nice. You should add these resources to an issue. Maybe someone picks it up and makes a PR. My priority is adding slow motion. As I need it for another project.

**Comment by blurtime** [comment]
Did you have a chance to test it?

**Comment by eonist** [comment]
I will test tonight for sure. And merge 👍

**Comment by blurtime** [comment]
Don't want to be annoying but no time at all yesterday? 😅

**Comment by eonist** [comment]
Yeah. Checked. forgot to merge.

**Comment by eonist** [comment]
And great job. Thanks for the PR 👍

**Comment by blurtime** [comment]
Thank you so much - especially for helping me out so many times already! I'll try to add the feature to switch the camera while recording asap (probably in about 2-3 weeks). Really loved working with you so far! 😊

**Pull request merged**
